// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: LvglWiFiConnect

#ifndef _LVGLWIFICONNECT_UI_H
#define _LVGLWIFICONNECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_events.h"
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_RollerWiFiAP;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_TextWiFiPassword;
extern lv_obj_t *ui_ButtonWiFiConnect;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Spinner1;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Screen3;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_TextVNCHost;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_TextVNCPort;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_TextVNCPassword;
extern lv_obj_t *ui_ButtonVNCConnect;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui____initial_actions0;




LV_FONT_DECLARE( ui_font_Cubic11);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
